# Generated by Django 3.1 on 2020-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
