# Generated by Django 3.1 on 2020-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qbank', '0002_auto_20200918_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
